---
- name: keydb-active-replication-redis-exporter | Check if redis_exporter already installed
  ansible.builtin.stat: path=/usr/local/bin/redis_exporter
  register: redis_exporter_bin

- name: keydb-active-replication-redis-exporter | Begin install redis_exporter
  block:
    - name: keydb-active-replication-redis-exporter | Download redis_exporter release
      ansible.builtin.get_url:
        url: '{{ redis_exporter_packages.url }}'
        dest: /usr/local/src/
        checksum: '{{ redis_exporter_packages.checksum }}'
      register: redis_exporter_src

    - name: keydb-active-replication-redis-exporter | Extract redis_exporter-*.tar.gz
      ansible.builtin.unarchive:
        src: '{{ redis_exporter_src.dest }}'
        remote_src: yes
        dest: /usr/local/bin/
        mode: 0755
        owner: root
        group: root
        extra_opts: ['--strip', '1']

    - name: keydb-active-replication-redis-exporter | Remove junk files
      ansible.builtin.file:
        path: /usr/local/bin/{{ item }}
        state: absent
      with_items:
        - LICENSE
        - NOTICE
        - README.md

  when: redis_exporter_bin.stat.exists == False

- name: keydb-active-replication-redis-exporter | Create redis-exporter systemd service
  ansible.builtin.template:
    src: systemd/redis-exporter.service.j2
    dest: '/usr/lib/systemd/system/redis-exporter.service'
    owner: root
    group: root
    mode: 0644
  notify: restart redis-exporter