---
- name: systemd reload
  systemd:
    daemon_reload: yes

- name: restart keydb
  systemd:
    name: keydb
    daemon_reload: True
    enabled: True
    state: restarted

- name: restart redis-exporter
  systemd:
    name: redis-exporter
    daemon_reload: True
    enabled: True
    state: restarted

- name: Warning file /etc/keydb/keydb.conf has been changed
  debug:
    msg: "Warning: file /etc/keydb/keydb.conf has been changed. Please review your change before restart keydb."