---
scenario:
  default:
    - lint
    - converge
    - verify
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: vm-dev-keydb-infra-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: infra
  - name: vm-dev-keydb-infra-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: infra
  - name: vm-dev-keydb-shopping-0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: shopping
  - name: vm-dev-keydb-shopping-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: shopping
  - name: vm-dev-keydb-shopping-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: shopping
provisioner:
  name: ansible
  log: true
  ansible_args:
    - --inventory=tests/inventory
  config_options:
    defaults:
      deprecation_warnings: false
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: ansible
